---
# not overridden
fromDefault: Hello World!

# overidden by test
fromTest: set by default.yaml

# overidden by test and ENV_MAP
fromEnv: set by default.yaml

fromExt: set by default.yaml

fromLocal: set by default.yaml

it:
  is:
    deep: deeep

env_mapped: set by default.yaml
